language: python
python:
    - "2.7"
cache: pip
install:
    - pip install -r requirements.txt
    - pip install coverage coveralls nosexcover
script: nosetests -v --cover-package=knowhow --with-xcoverage
after_success:
    - coveralls
